services:
  antigravity:
    image: rawritude/antigravity-remote-docker:latest
    container_name: antigravity
    restart: unless-stopped
    privileged: true
    shm_size: "2gb"
    network_mode: host
    environment:
      - VNC_PASSWORD=fernando
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ${APP_DATA_DIR}/workspace:/workspace
      - ${APP_DATA_DIR}/config:/config
    ports:
      - "3010:3000"
